server:
  port: 9191

spring:
  application:
    name: API_GATEWAY    
  cloud:
    gateway:
      routes:      - id: BOOKCATALOG-SERVICE
        uri: lb://BOOKCATALOG-SERVICE
        predicates:          - Path=/bookcatalog/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost